import { useEffect, useState } from 'react'
import { BookHeart, CalendarDays, ChevronRight, FilePenLine, Home, Plus, Search, Sparkles, X } from 'lucide-react'
import { CalendarView } from './components/CalendarView'
import { EntryDetail } from './components/EntryDetail'
import { JournalForm } from './components/JournalForm'
import { deleteEntry, fetchEntries, saveEntry } from './services/journalService'
import type { EntryInput, JournalEntry } from './types'

type View = 'today' | 'journal' | 'calendar' | 'detail' | 'edit'
const today = new Date().toISOString().slice(0, 10)
function formatDate(date: string) { return new Date(`${date}T12:00:00`).toLocaleDateString('nl-NL', { day: 'numeric', month: 'long', year: 'numeric' }) }

export default function App() {
  const [entries, setEntries] = useState<JournalEntry[]>([])
  const [view, setView] = useState<View>('today')
  const [selected, setSelected] = useState<JournalEntry | undefined>()
  const [loading, setLoading] = useState(true)
  const [notice, setNotice] = useState('')

  useEffect(() => { setLoading(true); fetchEntries().then(setEntries).catch(() => setNotice('Je entries konden niet worden geladen. Controleer je Supabase-configuratie.')).finally(() => setLoading(false)) }, [])
  useEffect(() => { if (notice) { const timer = setTimeout(() => setNotice(''), 4000); return () => clearTimeout(timer) } }, [notice])
  if (loading) return <div className="loading-screen"><BookHeart size={30} /><p>Je momenten worden opgehaald...</p></div>
  const todayEntry = entries.find(entry => entry.entry_date === today)
  const open = (entry: JournalEntry) => { setSelected(entry); setView('detail') }
  async function handleSave(input: EntryInput, id?: string) { const saved = await saveEntry(input, id); setEntries(current => id ? current.map(item => item.id === id ? saved : item) : [saved, ...current]); setSelected(saved); setNotice(id ? 'Je wijzigingen zijn bewaard.' : 'Je moment is opgeslagen.'); setView('detail') }
  async function handleDelete() { if (!selected || !window.confirm('Weet je zeker dat je deze entry wilt verwijderen? Dit kan niet ongedaan worden gemaakt.')) return; await deleteEntry(selected.id); setEntries(current => current.filter(item => item.id !== selected.id)); setSelected(undefined); setView('journal'); setNotice('De entry is verwijderd.') }
  const greeting = new Date().getHours() < 12 ? 'Goedemorgen' : new Date().getHours() < 18 ? 'Goedemiddag' : 'Goedenavond'
  return <div className="app-shell"><aside className="sidebar"><div className="logo"><BookHeart size={20} /> <span>moment</span></div><nav><button className={view === 'today' ? 'active' : ''} onClick={() => setView('today')}><Home size={18} /> Vandaag</button><button className={view === 'journal' || view === 'detail' || view === 'edit' ? 'active' : ''} onClick={() => setView('journal')}><FilePenLine size={18} /> Mijn dagboek</button><button className={view === 'calendar' ? 'active' : ''} onClick={() => setView('calendar')}><CalendarDays size={18} /> Kalender</button></nav><div className="sidebar-bottom"><div className="user-chip"><BookHeart size={18} /><span>Jouw persoonlijke ruimte</span></div></div></aside><main className="main-content"><div className="mobile-top"><div className="logo"><BookHeart size={20} /> <span>moment</span></div></div>{notice && <div className="toast"><Sparkles size={16} /> {notice}<button onClick={() => setNotice('')}><X size={15} /></button></div>}{view === 'today' && <Dashboard greeting={greeting} todayEntry={todayEntry} entries={entries} onWrite={() => { setSelected(todayEntry); setView(todayEntry ? 'detail' : 'edit') }} onOpen={open} onJournal={() => setView('journal')} />}{view === 'journal' && <JournalList entries={entries} onOpen={open} onWrite={() => { setSelected(undefined); setView('edit') }} />}{view === 'calendar' && <CalendarView entries={entries} onSelect={open} />}{view === 'detail' && selected && <EntryDetail entry={selected} onBack={() => setView('journal')} onEdit={() => setView('edit')} onDelete={handleDelete} />}{view === 'edit' && <JournalForm entry={selected} onSave={handleSave} onCancel={() => setView(selected ? 'detail' : 'today')} />}</main></div>
}

function Dashboard({ greeting, todayEntry, entries, onWrite, onOpen, onJournal }: { greeting: string; todayEntry?: JournalEntry; entries: JournalEntry[]; onWrite: () => void; onOpen: (entry: JournalEntry) => void; onJournal: () => void }) { return <div className="dashboard"><header className="welcome"><p className="eyebrow">{new Date().toLocaleDateString('nl-NL', { weekday: 'long', day: 'numeric', month: 'long' })}</p><h1>{greeting}, klaar om even<br /><em>terug te kijken?</em></h1><p>Een moment van aandacht voor jezelf maakt ruimte voor morgen.</p><button className="primary-button hero-button" onClick={onWrite}>{todayEntry ? <><FilePenLine size={18} /> Bekijk je dag van vandaag</> : <><Plus size={18} /> Schrijf over vandaag</>}</button></header><section className="recent-section"><div className="section-heading"><div><p className="eyebrow">JOUW MOMENTEN</p><h2>Recente entries</h2></div><button className="link-button" onClick={onJournal}>Bekijk alles <ChevronRight size={16} /></button></div>{entries.length ? <div className="entry-grid">{entries.slice(0, 3).map(entry => <EntryCard key={entry.id} entry={entry} onClick={() => onOpen(entry)} />)}</div> : <div className="empty-state"><div><Search size={22} /></div><h3>Je eerste moment wacht nog</h3><p>Schrijf vandaag iets op. Het hoeft maar een paar zinnen te zijn.</p></div>}</section></div> }
function EntryCard({ entry, onClick }: { entry: JournalEntry; onClick: () => void }) { return <button className="entry-card" onClick={onClick}><div className="card-top"><span>{formatDate(entry.entry_date)}</span><span>{entry.mood === 'great' ? '😄' : entry.mood === 'good' ? '🙂' : entry.mood === 'neutral' ? '😐' : entry.mood === 'low' ? '😕' : '😞'}</span></div><p>{entry.answer_1 || 'Geen antwoord ingevuld.'}</p><span className="read-link">Lees entry <ChevronRight size={15} /></span></button> }
function JournalList({ entries, onOpen, onWrite }: { entries: JournalEntry[]; onOpen: (entry: JournalEntry) => void; onWrite: () => void }) { return <div className="journal-page"><div className="section-heading"><div><p className="eyebrow">ARCHIEF</p><h1>Mijn dagboek</h1><p className="muted">{entries.length} {entries.length === 1 ? 'moment' : 'momenten'} verzameld</p></div><button className="primary-button" onClick={onWrite}><Plus size={17} /> Nieuwe entry</button></div>{entries.length ? <div className="all-entries">{entries.map(entry => <EntryCard key={entry.id} entry={entry} onClick={() => onOpen(entry)} />)}</div> : <div className="empty-state large"><div><BookHeart size={24} /></div><h3>Nog geen entries</h3><p>Begin met een klein moment van vandaag.</p><button className="primary-button" onClick={onWrite}><Plus size={17} /> Eerste entry schrijven</button></div>}</div> }